locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]
[[paths]]
reference = "templates/pages/homepage/what-we-fund.pot"
l10n = "locales/{locale}/pages/homepage/what-we-fund.po"
locales = [ "de", "es", "fr",]

[[paths]]
reference = "templates/pages/homepage.pot"
l10n = "locales/{locale}/pages/homepage.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.FocusArea/3-shape-the-agenda.pot"
l10n = "locales/{locale}/snippets/wagtailpages.FocusArea/3-shape-the-agenda.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.Petition/22-publishers_campaign_misinformation.pot"
l10n = "locales/{locale}/snippets/wagtailpages.Petition/22-publishers_campaign_misinformation.po"
locales = [ "de", "es", "fr",]

[[paths]]
reference = "templates/pages/homepage/campaigns/eu-misinformation/thanks.pot"
l10n = "locales/{locale}/pages/homepage/campaigns/eu-misinformation/thanks.po"
locales = [ "de", "es", "fr",]

[[paths]]
reference = "templates/pages/homepage/campaigns/eu-misinformation.pot"
l10n = "locales/{locale}/pages/homepage/campaigns/eu-misinformation.po"
locales = [ "de", "es", "fr",]

[[paths]]
reference = "templates/pages/homepage/campaigns/eu-misinformation/publisher-campaign/thanks-guardian.pot"
l10n = "locales/{locale}/pages/homepage/campaigns/eu-misinformation/publisher-campaign/thanks-guardian.po"
locales = [ "de", "fr",]

[[paths]]
reference = "templates/snippets/wagtailpages.FocusArea/1-rally-citizens.pot"
l10n = "locales/{locale}/snippets/wagtailpages.FocusArea/1-rally-citizens.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/pages/homepage/what-we-do.pot"
l10n = "locales/{locale}/pages/homepage/what-we-do.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/pages/homepage/campaigns/eu-misinformation/resources.pot"
l10n = "locales/{locale}/pages/homepage/campaigns/eu-misinformation/resources.po"
locales = [ "de", "es", "fr",]

[[paths]]
reference = "templates/pages/homepage/campaigns/eu-misinformation/action.pot"
l10n = "locales/{locale}/pages/homepage/campaigns/eu-misinformation/action.po"
locales = [ "de", "es", "fr",]

[[paths]]
reference = "templates/pages/homepage/newsletter.pot"
l10n = "locales/{locale}/pages/homepage/newsletter.po"
locales = [ "de", "es", "fr", "pt-BR",]

[[paths]]
reference = "templates/snippets/wagtailpages.Signup/35-minimalist-signup-snippet.pot"
l10n = "locales/{locale}/snippets/wagtailpages.Signup/35-minimalist-signup-snippet.po"
locales = [ "de", "es", "fr", "pt-BR",]

[[paths]]
reference = "templates/pages/homepage/campaigns/privacy-and-security-video-chat.pot"
l10n = "locales/{locale}/pages/homepage/campaigns/privacy-and-security-video-chat.po"
locales = [ "de", "es", "fr",]

[[paths]]
reference = "templates/snippets/wagtailpages.FocusArea/2-connect-leaders.pot"
l10n = "locales/{locale}/snippets/wagtailpages.FocusArea/2-connect-leaders.po"
locales = [ "de", "es", "fr", "fy-NL", "nl", "pl", "pt-BR",]

[[paths]]
reference = "templates/pages/homepage/campaigns/eu-misinformation/publisher-campaign.pot"
l10n = "locales/{locale}/pages/homepage/campaigns/eu-misinformation/publisher-campaign.po"
locales = [ "de", "es", "fr",]

